@isTest
public class Indian_currency_FormatTest {
    @isTest static void testtest(){
        Indian_currency_Format num1=new Indian_currency_Format();
        Indian_currency_Format.test('100');
        Indian_currency_Format.test('1000');
        Indian_currency_Format.test('10000');
        Indian_currency_Format.test('100000');
        Indian_currency_Format.test('1000000');
        Indian_currency_Format.test('100000000');
        Indian_currency_Format.test('1000000000');
        Indian_currency_Format.test('10000000000');
        Indian_currency_Format.test('100000000000');
        Indian_currency_Format.test('1000000000000');
        Indian_currency_Format.test('10000000000000');
        Indian_currency_Format.test('100000000000000');
               
       
        
    }
}